services:
  postgresql:
    image: postgres:15
    container_name: postgresql-stock-management
    restart: always
    environment:
      POSTGRES_DB: stockmanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5436:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - postgresql_network

volumes:
  postgresql_data:
    driver: local

networks:
  postgresql_network:
    driver: bridge